#+TITLE: \textsc{Marius Peter}
#+OPTIONS: toc:nil num:nil date:nil

#+LATEX_HEADER: \usepackage{fullpage}
# #+LATEX_HEADER: \usepackage{mathptmx}


|Sales $\star$ Engineering $\star$ Design|

|                <c>                |
|   11090 Strathmore Dr, Apt #1,    |
|          Los Angeles, CA          |
| [[mailto:mpeter@ucla.edu][mpeter@ucla.edu]] / +1 818 284 3757 |

    - *Sales*: secured initial funding for an industrial process modelling tool
      designed for the European aerospace sector
    - *Engineering*: UCLA B.S. Aerospace Eng., 10 year Linux user (desktop,
      server & embedded)
    - Seeking a *sales engineering* mission within the American industrial
      sector for September 2019

* Education

** B.S. in Aerospace Engineering
- 2014--2019 :: B.S. in Aerospace Engineering --- University of California, Los Angeles
- Technical breadth in Technology & Management
- Electives: biomechanics, RFID and its application in manufacturing \& supply chain
- PID Controller Design \textbullet
  Fluid Mechanics \textbullet
  Thermodynamics \textbullet
  Aircraft Propulsion \textbullet

* Work

- Sep.--Dec. 2017 :: Assistant Business Analyst --- Cosmo Tech, Lyon
  - Cosmo Tech publishes a Decision Support Software for complex systems (road networks, energy grids)
  - Created & presented a proof of concept for Airbus' \textit{digital continuity} strategy using principles of Model-Based Systems Engineering
  - Showcased Cosmo’s simulation capabilities for \textit{Shop Floor Control} and \textit{Final Assembly Line}
  - Secured initial funding for a bespoke software solution developed for Airbus
- June--July 2015 :: Assistant Electronics Engineer --- CERN, Geneva
  - Learned HDL, LabVIEW and core concepts of hardware programming
  - Upgraded FPGA data acquisition systems from CLIs to GUIs (embedded ARM Linux)
- Apr.--May 2012 :: Engineering Intern --- Alcatel Submarine Networks, Paris
  - Learned the internal workings of an international optical fiber deployment company
  - Assisted the Product Line Manager in evaluating ASN's current offering vs European competitors

* Projects
** UCLA Design--Build--Launch
- Model rocket design, manufacturing, testing & analysis
- Lead the manufacturing of my team's rocket: mill & lathe, 3D printing, fiberglass, plywood...
- We won first place on all criteria: maximum apogee, intact payload, trajectory prediction...

** Aircraft Studio [[https:www.github.com/Blendoit/Aircraft_Studio]]
- Broadened the scope of development of a program written for UCLA's aircraft design course
- Initial goal: design FAR 23 compliant NACA airfoils and optimize for weight using a genetic algorithm
- Ultimate goal: develop an integrated aircraft creation suite designed for non-technical persons

** Solidworks/Blender [[https:www.deviantart.com/faquinou]]
- 7 years experience in geometry modeling, texturing, rendering & visual FX

\cventry{Apr.--June 2019}{UCLA Design--Build--Launch}{Senior Capstone}
\cventry{Apr. 2019--Pres.}{Aircraft Studio}{Python \url{}}
\cventry{2012--Pres.}{3D Design/CAD}{ \url{}}

* Certifications & Licenses
- Dec. 2019 :: Linux Foundation Certified Engineer
  - Advanced Linux administration and engineering
- Mar. 2019 :: LEED Green Associate
  - Sustainable building design, construction, and operations

* Skills

| _Computer Science_                         | _Systems & Industrial_           | _Languages_                      |
| Microsoft Suite & \LaTeX                   | UML, SysML, BPMN                 | Native: French, English          |
| Languages: Verilog, MATLAB, Python, Tcl/Tk | AnyLogic, SIMPROCESS, MEGA HOPEX | Proficient: German               |
| CAD packages: SOLIDWORKS, Blender 3D       |                                  | Intermediate: Chinese (Mandarin) |
